// Maps granular question-level controlSlug values to the 30 valid
// control page slugs defined in lib/controls.js.  The Tooltip component
// uses this so "Learn more →" links always resolve to a real page.

const VALID_SLUGS = new Set([
  "multi-factor-authentication",
  "password-management",
  "access-control-policy",
  "employee-offboarding",
  "access-review",
  "data-encryption",
  "data-backup",
  "backup-testing",
  "data-classification",
  "data-retention",
  "endpoint-protection",
  "patch-management",
  "device-encryption",
  "byod-policy",
  "remote-wipe",
  "email-filtering",
  "phishing-training",
  "email-authentication",
  "email-reporting",
  "network-segmentation",
  "firewall-management",
  "vpn-remote-access",
  "network-monitoring",
  "incident-response-plan",
  "emergency-contacts",
  "cyber-insurance",
  "vendor-risk-management",
  "vendor-agreements",
  "security-training",
  "security-onboarding",
])

// Keyword fragments → valid slug. Order matters: first match wins.
const KEYWORD_RULES = [
  ["mfa", "multi-factor-authentication"],
  ["password", "password-management"],
  ["offboarding", "employee-offboarding"],
  ["seasonal-worker", "employee-offboarding"],
  ["access-review", "access-review"],
  ["encryption", "data-encryption"],
  ["tokenization", "data-encryption"],
  ["backup", "data-backup"],
  ["disaster-recovery", "data-backup"],
  ["recovery-time", "data-backup"],
  ["rto-rpo", "data-backup"],
  ["business-continuity", "data-backup"],
  ["restoration", "data-backup"],
  ["recovery-procedures", "data-backup"],
  ["matter-archive", "data-backup"],
  ["data-classification", "data-classification"],
  ["document-classification", "data-classification"],
  ["cui-marking", "data-classification"],
  ["cui-storage", "data-classification"],
  ["cui-data-flow", "data-classification"],
  ["minimum-necessary", "data-classification"],
  ["phi-data", "data-classification"],
  ["phi-deidentification", "data-classification"],
  ["cardholder-data", "data-classification"],
  ["data-loss-prevention", "data-classification"],
  ["cui-media", "data-classification"],
  ["receipt-data", "data-classification"],
  ["data-retention", "data-retention"],
  ["secure-disposal", "data-retention"],
  ["secure-data-disposal", "data-retention"],
  ["cui-secure-disposal", "data-retention"],
  ["log-retention", "data-retention"],
  ["endpoint-protection", "endpoint-protection"],
  ["malicious-code", "endpoint-protection"],
  ["pos-endpoint", "endpoint-protection"],
  ["server-hardening", "endpoint-protection"],
  ["baseline-config", "endpoint-protection"],
  ["configuration-monitor", "endpoint-protection"],
  ["software-restriction", "endpoint-protection"],
  ["system-integrity", "endpoint-protection"],
  ["asset-tracking", "endpoint-protection"],
  ["payment-terminal", "endpoint-protection"],
  ["medical-device-inventory", "endpoint-protection"],
  ["patch", "patch-management"],
  ["os-patching", "patch-management"],
  ["flaw-remediation", "patch-management"],
  ["change-management", "patch-management"],
  ["byod", "byod-policy"],
  ["mobile-device", "byod-policy"],
  ["usb-media", "byod-policy"],
  ["remote-wipe", "remote-wipe"],
  ["email-security", "email-filtering"],
  ["spam-protection", "email-filtering"],
  ["email-encryption", "email-filtering"],
  ["secure-messaging", "email-filtering"],
  ["secure-file", "email-filtering"],
  ["phishing", "phishing-training"],
  ["social-engineering", "phishing-training"],
  ["dmarc", "email-authentication"],
  ["business-email-domain", "email-authentication"],
  ["business-domain", "email-authentication"],
  ["customer-communication-security", "email-authentication"],
  ["suspicious-email", "email-reporting"],
  ["suspicious-activity", "email-reporting"],
  ["network-segment", "network-segmentation"],
  ["cui-network", "network-segmentation"],
  ["cde-segment", "network-segmentation"],
  ["wifi", "network-segmentation"],
  ["wireless", "network-segmentation"],
  ["boundary-protection", "network-segmentation"],
  ["collaborative-computing", "network-segmentation"],
  ["medical-device-segmentation", "network-segmentation"],
  ["session-authenticity", "network-segmentation"],
  ["firewall", "firewall-management"],
  ["network-access-control", "firewall-management"],
  ["ids", "firewall-management"],
  ["vpn", "vpn-remote-access"],
  ["remote-access", "vpn-remote-access"],
  ["remote-work", "vpn-remote-access"],
  ["network-monitor", "network-monitoring"],
  ["network-access-review", "network-monitoring"],
  ["siem", "network-monitoring"],
  ["audit-log", "network-monitoring"],
  ["log-review", "network-monitoring"],
  ["audit-record", "network-monitoring"],
  ["system-level-monitor", "network-monitoring"],
  ["infrastructure-monitor", "network-monitoring"],
  ["security-alerts", "network-monitoring"],
  ["penetration-test", "network-monitoring"],
  ["continuous-monitoring", "network-monitoring"],
  ["vulnerability-scanning", "network-monitoring"],
  ["threat-intelligence", "network-monitoring"],
  ["transaction-monitoring", "network-monitoring"],
  ["fraud-detection", "network-monitoring"],
  ["incident-response", "incident-response-plan"],
  ["ir-plan", "incident-response-plan"],
  ["ir-team", "incident-response-plan"],
  ["ir-testing", "incident-response-plan"],
  ["incident-tracking", "incident-response-plan"],
  ["breach-notification", "incident-response-plan"],
  ["incident-reporting", "incident-response-plan"],
  ["dfars", "incident-response-plan"],
  ["regulatory-notification", "incident-response-plan"],
  ["client-notification", "incident-response-plan"],
  ["bar-association", "incident-response-plan"],
  ["pci-breach", "incident-response-plan"],
  ["customer-notification", "incident-response-plan"],
  ["ocr-breach", "incident-response-plan"],
  ["forensic", "incident-response-plan"],
  ["poam-tracking", "incident-response-plan"],
  ["emergency-contacts", "emergency-contacts"],
  ["ir-plan-communication", "emergency-contacts"],
  ["cyber-insurance", "cyber-insurance"],
  ["insurance-coverage", "cyber-insurance"],
  ["insurance-status", "cyber-insurance"],
  ["vendor-risk", "vendor-risk-management"],
  ["vendor-inventory", "vendor-risk-management"],
  ["vendor-security", "vendor-risk-management"],
  ["vendor-access", "vendor-risk-management"],
  ["vendor-audit", "vendor-risk-management"],
  ["fourth-party", "vendor-risk-management"],
  ["soc2", "vendor-risk-management"],
  ["subcontractor", "vendor-risk-management"],
  ["supply-chain", "vendor-risk-management"],
  ["third-party-app", "vendor-risk-management"],
  ["cloud-service", "vendor-risk-management"],
  ["legal-tech-vendor", "vendor-risk-management"],
  ["ediscovery", "vendor-risk-management"],
  ["payment-processor", "vendor-risk-management"],
  ["pos-vendor", "vendor-risk-management"],
  ["phi-sharing", "vendor-risk-management"],
  ["vendor-data-agreement", "vendor-agreements"],
  ["data-sharing-agreement", "vendor-agreements"],
  ["baa-compliance", "vendor-agreements"],
  ["security-training", "security-training"],
  ["security-awareness", "security-training"],
  ["training-program", "security-training"],
  ["employee-training", "security-training"],
  ["acceptable-use", "security-training"],
  ["insider-threat", "security-training"],
  ["role-based-training", "security-training"],
  ["cui-training", "security-training"],
  ["pci-awareness", "security-training"],
  ["phi-handling", "security-training"],
  ["new-hire", "security-onboarding"],
  // Compliance / governance → security-training (closest general control)
  ["hipaa", "security-training"],
  ["cmmc", "security-training"],
  ["glba", "security-training"],
  ["aba-ethics", "security-training"],
  ["ssp-documentation", "security-training"],
  ["risk-assessment", "security-training"],
  ["risk-management", "security-training"],
  ["information-security-program", "security-training"],
  ["security-policy", "security-training"],
  ["board-management", "security-training"],
  ["c3pao", "security-training"],
  // Access-related fallbacks
  ["access-control", "access-control-policy"],
  ["privileged-access", "access-control-policy"],
  ["role-based-access", "access-control-policy"],
  ["session-management", "access-control-policy"],
  ["least-functionality", "access-control-policy"],
  ["personnel-screening", "access-control-policy"],
  ["cui-access", "access-control-policy"],
  ["employee-access", "access-control-policy"],
  ["conflict-walls", "access-control-policy"],
  ["authentication-policy", "password-management"],
  ["encrypted-communication", "data-encryption"],
  // Payment / PCI → data-encryption
  ["pci", "data-encryption"],
  ["payment", "data-encryption"],
  ["ecommerce", "data-encryption"],
  ["wire-transfer", "data-encryption"],
  ["trust-account", "data-encryption"],
]

export function resolveControlSlug(slug) {
  if (!slug) return null
  if (VALID_SLUGS.has(slug)) return slug
  for (const [keyword, validSlug] of KEYWORD_RULES) {
    if (slug.includes(keyword)) return validSlug
  }
  return null
}
