export const POLICIES = [
  {
    slug: "information-security-policy",
    name: "Information Security Policy",
    shortName: "Master Policy",
    description: "The governing policy that establishes your organization's security framework and references all sub-policies.",
    estimatedMinutes: 8,
    free: true,
    sections: 7,
  },
  {
    slug: "acceptable-use-policy",
    name: "Acceptable Use Policy",
    shortName: "Acceptable Use",
    description: "Defines appropriate and prohibited use of technology resources by employees and contractors.",
    estimatedMinutes: 7,
    free: true,
    sections: 7,
  },
  {
    slug: "incident-response-plan",
    name: "Incident Response Plan",
    shortName: "Incident Response",
    description: "Step-by-step procedures for detecting, containing, and recovering from security incidents.",
    estimatedMinutes: 10,
    free: false,
    sections: 10,
  },
  {
    slug: "business-continuity-plan",
    name: "Business Continuity & Disaster Recovery Plan",
    shortName: "BCP / DR",
    description: "Ensures your organization can continue operating during and after a disruptive event.",
    estimatedMinutes: 10,
    free: false,
    sections: 10,
  },
  {
    slug: "data-classification-policy",
    name: "Data Classification & Handling Policy",
    shortName: "Data Classification",
    description: "Categorizes your data by sensitivity level and defines handling requirements for each.",
    estimatedMinutes: 8,
    free: false,
    sections: 9,
  },
  {
    slug: "access-control-policy",
    name: "Access Control & Password Policy",
    shortName: "Access Control",
    description: "Governs user authentication, authorization, and password requirements across all systems.",
    estimatedMinutes: 8,
    free: false,
    sections: 9,
  },
  {
    slug: "remote-work-byod-policy",
    name: "Remote Work & BYOD Policy",
    shortName: "Remote / BYOD",
    description: "Requirements for secure remote work arrangements and personal device use on company networks.",
    estimatedMinutes: 7,
    free: false,
    sections: 8,
  },
  {
    slug: "vendor-management-policy",
    name: "Vendor & Third-Party Risk Management Policy",
    shortName: "Vendor Risk",
    description: "Due diligence, monitoring, and security requirements for all third-party vendors and service providers.",
    estimatedMinutes: 8,
    free: false,
    sections: 8,
  },
  {
    slug: "ai-acceptable-use-policy",
    name: "AI Acceptable Use Policy",
    shortName: "AI Use Policy",
    description: "Standards and guardrails for the responsible use of AI tools and generative AI in your organization.",
    estimatedMinutes: 9,
    free: false,
    sections: 11,
  },
]

export function getPolicyBySlug(slug) {
  return POLICIES.find((p) => p.slug === slug)
}
